/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Component;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.categoriaDatos;
import model.categoriaModel;

/**
 *
 * @author mlang
 */
public class CategoriaForm extends javax.swing.JDialog {

    /**
     * Creates new form CategoriaForm
     */
    //ArrayList para almacenar los datos de la consulta
    ArrayList<Object[]> data = new ArrayList<>();

    //Creando instancias de modelo y datos
    categoriaModel model = new categoriaModel();
    categoriaModel model1 = new categoriaModel();
    categoriaDatos datos = new categoriaDatos();

    //Variable para asignar el valor de las categorias
    private ArrayList<Object> valor = new ArrayList<>();

    //Creando el modelo de la tabla
    DefaultTableModel tableModel = new DefaultTableModel();

    public CategoriaForm(Component parent, boolean modal) {
        super((Frame) SwingUtilities.getWindowAncestor(parent), modal);
        initComponents();

        //Asignando valores a los atributos
        model.setOPCION(0);
        model.setPK_TBL_PMK_CATEGORIA(0);
        model.setUSUARIO("MAURICE.LANG");
        model.setCATEGORIA("");

        //Guardando los datos en la arraylist
        data = datos.obtenerDatos(model);

        //Añadiendo las columnas a la tabla
        tableModel.addColumn("ID");
        tableModel.addColumn("CATEGORIA");

        //Leyendo los datos por medio de un for each
        for (Object[] fila : data) {
            tableModel.addRow(fila);
        }

        //Agregando los datos a la tabla
        tblCategorias.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        txtCategoria = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(123, 158, 171));

        tblCategorias = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCategorias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategorias);

        txtCategoria.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N
        txtCategoria.setPreferredSize(new java.awt.Dimension(77, 39));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N
        txtId.setPreferredSize(new java.awt.Dimension(77, 39));

        btnAgregar.setBackground(new java.awt.Color(234, 234, 234));
        btnAgregar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plus.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(234, 234, 234));
        btnModificar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pencil.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(234, 234, 234));
        btnEliminar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/trash.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(234, 234, 234));
        btnBuscar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriasMouseClicked
        //Condicional para saber si da 1 o 2 clicks
        if (evt.getClickCount() == 2) {
            //Obtiene la posicion donde se hizo el click
            int filaSeleccionada = tblCategorias.getSelectedRow();
            //Se realiza una condicional para determinar si la fila seleccionada es mayor o igual a 0
            if (filaSeleccionada >= 0) {
                //Se crea una instacia de ArrayList
                ArrayList<Object> datosFila = new ArrayList<>();
                //Se empieza a recorrer la tabla para obtener los valores de la fila seleccionada
                for (int i = 0; i < tableModel.getColumnCount(); i++) {
                    datosFila.add(tableModel.getValueAt(filaSeleccionada, i));
                }

                //Se guarda el valor de la tabla en una variable
                valor = datosFila;
                dispose();
            }
        } else {
            //Obtiene la posicion donde se hizo el click
            int filaSeleccionada = tblCategorias.getSelectedRow();
            //Se realiza una condicional para determinar si la fila seleccionada es mayor o igual a 0
            if (filaSeleccionada >= 0) {
                //Se crea una instacia de ArrayList
                ArrayList<Object> datosFila = new ArrayList<>();
                //Se empieza a recorrer la tabla para obtener los valores de la fila seleccionada
                for (int i = 0; i < tableModel.getColumnCount(); i++) {
                    datosFila.add(tableModel.getValueAt(filaSeleccionada, i));
                }

                //Agregan los datos a los textfield
                txtId.setText(datosFila.get(0).toString());
                txtCategoria.setText(datosFila.get(1).toString());
            }
        }
    }//GEN-LAST:event_tblCategoriasMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //Atributos
        model.setOPCION(0);
        model.setUSUARIO("MAURICE.LANG");

        //Condicional para validar si el campo id tiene un valor
        if (!txtId.getText().equals("")) {
            model.setPK_TBL_PMK_CATEGORIA(Integer.parseInt(txtId.getText()));
        } else {
            model.setPK_TBL_PMK_CATEGORIA(0);
        }

        model.setCATEGORIA(txtCategoria.getText().toUpperCase());

        //Condicional para saber si se hizo la transaccion
        if (datos.ingresar(model)) {
            JOptionPane.showMessageDialog(null, "Ingresado con exito");
            limpiar();

            model1.setOPCION(0);
            model1.setUSUARIO("MAURICE.LANG");
            model1.setPK_TBL_PMK_CATEGORIA(0);
            model1.setCATEGORIA("");

            data = null;
            tableModel.setRowCount(0);

            data = datos.obtenerDatos(model1);

            for (Object[] fila : data) {
                tableModel.addRow(fila);
            }

            //Agregando los datos a la tabla
            tblCategorias.setModel(tableModel);
        } else {
            JOptionPane.showMessageDialog(null, "Error al ingresar");
            limpiar();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Atributos
        model.setOPCION(0);
        model.setUSUARIO("MAURICE.LANG");

        //Condicional para validar si el campo id tiene un valor
        if (!txtId.getText().equals("")) {
            model.setPK_TBL_PMK_CATEGORIA(Integer.parseInt(txtId.getText()));
        } else {
            model.setPK_TBL_PMK_CATEGORIA(0);
        }

        model.setCATEGORIA(txtCategoria.getText().toUpperCase());

        //Condicional para saber si se hizo la transaccion
        if (datos.modificar(model)) {
            JOptionPane.showMessageDialog(null, "Modificado con exito");
            limpiar();

            model1.setOPCION(0);
            model1.setUSUARIO("MAURICE.LANG");
            model1.setPK_TBL_PMK_CATEGORIA(0);
            model1.setCATEGORIA("");

            data = null;
            tableModel.setRowCount(0);

            data = datos.obtenerDatos(model1);

            for (Object[] fila : data) {
                tableModel.addRow(fila);
            }

            //Agregando los datos a la tabla
            tblCategorias.setModel(tableModel);
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar");
            limpiar();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Atributos
        model.setOPCION(1);
        model.setUSUARIO("MAURICE.LANG");

        //Condicional para validar si el campo id tiene un valor
        if (!txtId.getText().equals("")) {
            model.setPK_TBL_PMK_CATEGORIA(Integer.parseInt(txtId.getText()));
        } else {
            model.setPK_TBL_PMK_CATEGORIA(0);
        }

        model.setCATEGORIA(txtCategoria.getText().toUpperCase());

        //Condicional para saber si se hizo la transaccion
        if (datos.ingresar(model)) {
            JOptionPane.showMessageDialog(null, "Eliminado con exito");
            limpiar();

            model1.setOPCION(0);
            model1.setUSUARIO("MAURICE.LANG");
            model1.setPK_TBL_PMK_CATEGORIA(0);
            model1.setCATEGORIA("");

            data = null;
            tableModel.setRowCount(0);

            data = datos.obtenerDatos(model1);

            for (Object[] fila : data) {
                tableModel.addRow(fila);
            }

            //Agregando los datos a la tabla
            tblCategorias.setModel(tableModel);
        } else {
            JOptionPane.showMessageDialog(null, "Error al elininar");
            limpiar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        model.setOPCION(0);
        model.setUSUARIO("MAURICE.LANG");

        //JOptionPane para saber el tipo de dato que desea buscar
        Object buscar = JOptionPane.showInputDialog(null, "Seleccione una Opcion", "Buscar", JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Seleccione", "Id", "Categoria"}, "Seleccione");

        //Variable para almacenar el dato
        String valor = JOptionPane.showInputDialog("Ingrese " + buscar + " para buscar: ");

        //Condicional para buscar por el tipo de dato elegido
        switch (buscar.toString()) {
            case "Id":
                //Atributos
                model.setPK_TBL_PMK_CATEGORIA(Integer.parseInt(valor));
                model.setCATEGORIA("");

                data = null;
                tableModel.setRowCount(0);

                data = datos.obtenerDatos(model);

                for (Object[] fila : data) {
                    tableModel.addRow(fila);
                }

                //Agregando los datos a la tabla
                tblCategorias.setModel(tableModel);
                break;
            case "Categoria":
                //Atributos
                model.setPK_TBL_PMK_CATEGORIA(0);
                model.setCATEGORIA(valor);

                data = null;
                tableModel.setRowCount(0);

                data = datos.obtenerDatos(model);

                for (Object[] fila : data) {
                    tableModel.addRow(fila);
                }

                //Agregando los datos a la tabla
                tblCategorias.setModel(tableModel);
                break;
            default:
                JOptionPane.showMessageDialog(null, "No es una opcion valida");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CategoriaForm dialog = new CategoriaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Object> obtenerValor() {
        setVisible(false);
        return valor;
    }

    private void limpiar() {
        txtId.setText("");
        txtCategoria.setText("");
    }
}
