/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Component;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Categoria;
import model.categoriaDatos;
import model.categoriaModel;
import model.inventarioDatos;
import model.inventarioModel;

/**
 *
 * @author mlang
 */
public class ProductoForm extends javax.swing.JDialog {

    /**
     * Creates new form ProductoForm
     */
    //ArrayList para almacenar los datos de la consulta
    ArrayList<Object[]> data = new ArrayList<>();
    ArrayList<Object[]> data1 = new ArrayList<>();

    //Creando instancias de modelo y datos
    categoriaModel model = new categoriaModel();
    inventarioModel model1 = new inventarioModel();
    categoriaDatos datos = new categoriaDatos();
    inventarioDatos datos1 = new inventarioDatos();

    //Variable para asignar el valor de las categorias
    private ArrayList<Object> valor = new ArrayList<>();

    //Creando el modelo de la tabla
    DefaultTableModel tableModel = new DefaultTableModel();

    //Creando el modelo del combobox
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

    //Variable para poder guardar el ID de la categoria
    private String Id;

    public ProductoForm(Component parent, boolean modal) {
        super((Frame) SwingUtilities.getWindowAncestor(parent), modal);
        initComponents();

        //Asignando valores a los atributos
        model.setOPCION(0);
        model.setPK_TBL_PMK_CATEGORIA(0);
        model.setUSUARIO("MAURICE.LANG");
        model.setCATEGORIA("");

        //Guardando los datos en la arraylist
        data = datos.obtenerDatos(model);

        ///Leyendo los datos por medio de un for each
        for (Object[] fila : data) {
            comboBoxModel.addElement(fila[1].toString());
        }

        cbxAreas.setModel(comboBoxModel);

        //Añadiendo las columnas a la tabla
        tableModel.addColumn("ID");
        tableModel.addColumn("CODIGO");
        tableModel.addColumn("NOMBRE");
        tableModel.addColumn("TIPO ANIMAL");
        tableModel.addColumn("PRECIO");
        tableModel.addColumn("CANTIDAD");
        tableModel.addColumn("CATEGORIA");

        tblProductos.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        cbxAreas = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(123, 158, 171));

        tblProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        cbxAreas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        cbxAreas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Areas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(234, 234, 234));
        btnBuscar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cbxAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Condicional para ver si el nombre se agrego o no
        if (txtNombre.getText().equals("")) {
            String valor = cbxAreas.getSelectedItem().toString();

            //Asignando valores a los atributos
            model.setOPCION(0);
            model.setPK_TBL_PMK_CATEGORIA(0);
            model.setUSUARIO("MAURICE.LANG");
            model.setCATEGORIA(valor);

            //Guardando los datos en la arraylist
            data = datos.obtenerDatos(model);

            Id = data.get(0)[0].toString();

            model1.setOPCION(0);
            model1.setPK_TBL_PMK_INVENTARIO(0);
            model1.setUSUARIO("MAURICE.LANG");
            model1.setCANTIDAD(0);
            model1.setCODIGO("");
            model1.setNOMBRE("");
            model1.setPRECIO(0.0);
            model1.setTIPO_ANIMAL("");
            model1.setID_CATEGORIA(Integer.parseInt(Id));

            data1 = null;
            tableModel.setRowCount(0);

            data1 = datos1.obtenerDatos(model1);

            //Leyendo los datos por medio de un for each
            for (Object[] fila : data1) {
                tableModel.addRow(fila);
            }

            //Agregando los datos a la tabla
            tblProductos.setModel(tableModel);
        } else {
            String valor = cbxAreas.getSelectedItem().toString();
            String valor1 = txtNombre.getText();

            //Asignando valores a los atributos
            model.setOPCION(0);
            model.setPK_TBL_PMK_CATEGORIA(0);
            model.setUSUARIO("MAURICE.LANG");
            model.setCATEGORIA(valor);

            //Guardando los datos en la arraylist
            data = datos.obtenerDatos(model);

            Id = data.get(0)[0].toString();

            model1.setOPCION(0);
            model1.setPK_TBL_PMK_INVENTARIO(0);
            model1.setUSUARIO("MAURICE.LANG");
            model1.setCANTIDAD(0);
            model1.setCODIGO("");
            model1.setNOMBRE(valor1);
            model1.setPRECIO(0.0);
            model1.setTIPO_ANIMAL("");
            model1.setID_CATEGORIA(Integer.parseInt(Id));

            data1 = null;
            tableModel.setRowCount(0);

            data1 = datos1.obtenerDatos(model1);

            //Leyendo los datos por medio de un for each
            for (Object[] fila : data1) {
                tableModel.addRow(fila);
            }

            //Agregando los datos a la tabla
            tblProductos.setModel(tableModel);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        //Obtiene la posicion donde se hizo el click
        int filaSeleccionada = tblProductos.getSelectedRow();
        //Se realiza una condicional para determinar si la fila seleccionada es mayor o igual a 0
        if (filaSeleccionada >= 0) {
            //Se crea una instacia de ArrayList
            ArrayList<Object> datosFila = new ArrayList<>();
            //Se empieza a recorrer la tabla para obtener los valores de la fila seleccionada
            for (int i = 0; i < tableModel.getColumnCount(); i++) {
                datosFila.add(tableModel.getValueAt(filaSeleccionada, i));
            }

            //Se guarda el valor de la tabla en una variable
            valor = datosFila;
            dispose();
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoForm dialog = new ProductoForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbxAreas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Object> obtenerValor() {
        setVisible(false);
        return valor;
    }
    
    public String obtenerId(){
        return Id;
    }
}
